remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /cgar1.github.io/Project_1_Coakley.md
  Project 2: /cgar1.github.io/Project2_coakley.md
  Project 3: /cgar1.github.io/Project3.md
  Project 4: /cgar1.github.io/Lab6_coakley.md  
